namespace :db do
  desc "Run migrations"
  task :migrate, [:version] do |t, args|
    require "sequel"
    require "yaml"
    Sequel.extension :migration
    config = YAML.load_file("etc/config.yml")
    case ENV['RACK_ENV']

    when "test"
      dbstring = "sqlite://db/test.db"
    when "development"
        dbstring = "sqlite://db/development.db"
    else
      dbstring = "sqlite://db/production.db"
    end
    db = Sequel.connect(dbstring)
    if args[:version]
      puts "Migrating to version #{args[:version]}"
      Sequel::Migrator.run(db, "db/migrations", target: args[:version].to_i)
    else
      puts "Migrating to latest"
      Sequel::Migrator.run(db, "db/migrations")
    end
  end
end

